#!/bin/bash

FOLDER=$1
DAYS=$2
DIVISOR=$3 # ~5.5 letters per word

cd "$FOLDER"

for i in $(seq $DAYS -1 0)
do
    GIT_DATE=$(date -v -${i}d +%Y-%m-%d)
    LAST_COMMIT=$(git rev-list --all --before="$GIT_DATE 24:00" | head -n 1)
    git checkout $LAST_COMMIT > /dev/null 2>&1
    SIZE=$(gdu --bytes --summarize --exclude=imagenes --exclude=media | awk '{print $1}')
    SCALED_SIZE=$(awk "BEGIN {printf \"%d\", $SIZE/$DIVISOR}")
    echo "$GIT_DATE $SCALED_SIZE"
done

git checkout main > /dev/null 2>&1
